-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.3.0.109
-- Module  Version: 5.6
-- Sun Apr 26 00:56:48 2015

-- parameterized module component declaration
component Sweet32_clkgen
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic);
end component;

-- parameterized module component instance
__ : Sweet32_clkgen
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__);
